presets:
  change_state:
    trigger: [[LSP, RSP], 1]
    action:
      - type: shared_values
        method: round_robin
        key: state
        values: ['chassis', 'state-1']
  publish_hello:
    trigger: X
    action:
      - type: publish
        topic:
          name: hello
          type: std_msgs/String
        values:
          data: 'Hello there (now going to sleep for a second)'
      - type: sleep
        duration: 1
      - type: publish
        topic:
          name: hello
          type: std_msgs/String
        values:
          data: 'Hello again!'
  only_state_1:
    trigger: [X, 1]
    enabled_states: ['state-1']
    action:
      - type: publish
        topic:
          name: hello
          type: std_msgs/String
        values:
          data: 'I only get published in state-1'
  cmd_vel:
    trigger: always
    enabled_states: ['chassis']
    action:
      - type: twist_2dof
        out_topic: cmd_vel
        frame_id: base_link
        scale:
          # Note: These values are overridden by scale changes
          translation: 1
          rotation: 1
        normal:
          v: LSV
          w: RSH
        beginner:
          v: LSV
          w: LSH
        tank:
          left: LSV
          right: RSV
  cmd_vel_mode:
    trigger: RSP
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: round_robin
        key: cmd_vel_mode
        values: ['normal', 'beginner', 'tank']
  increase_scale_translation:
    trigger: C_U
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: bidirectional
        direction: increment
        key: scale_translation
        values: [0.25, 0.5, 1.0]
  decrease_scale_translation:
    trigger: C_D
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: bidirectional
        direction: decrement
        decremental: true
        key: scale_translation
        values: [0.25, 0.5, 1.0]
  increase_scale_rotation:
    trigger: C_R
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: bidirectional
        direction: increment
        key: scale_rotation
        values: [0.25, 0.5, 1.0]
  decrease_scale_rotation:
    trigger: C_L
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: bidirectional
        direction: decrement
        decremental: true
        key: scale_rotation
        values: [0.25, 0.5, 1.0]
