rate: 50
timeout:
  press: 0.1
  sequence: 0.2

presets:
  super:
    trigger: [C_U, C_U, C_D, C_D, C_L, C_R, C_L, C_R, X, O]
    action:
      - type: publish_string
        topic: super
        include_time: true
        value: 'You found the secret command!'
